[package]
name = "bbachain-cli"
description = "BBACHAIN CLI"
documentation = "https://docs.rs/bbachain-cli"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
